import './styles/materialize.min.css';
import './styles/main.scss';
import './styles/modal.scss';
import './styles/form.scss';
import './styles/imaging.scss';
import './styles/masonry.scss';
import googleMaps from './js/googleMaps.js';
import loadImages from './js/imaging.js';
import masonry from './js/masonry.js';
import stickyNav from './js/stickyNav.js';
import linkScroll from './js/linkScroll.js';
import modal from './js/modal.js';
import form from './js/form.js';

stickyNav();
linkScroll();
loadImages();
modal();
form();
masonry();