// import 'materialize-css/dist/css/materialize.min.css';
require('materialize-css/dist/css/materialize.css');
require('./styles/main.scss');
require('./styles/modal.scss');
require('./styles/form.scss');
require('./styles/imaging.scss');
require('./styles/masonry.scss');
import googleMaps from './js/googleMaps.js';
import loadImages from './js/imaging.js';
import masonry from './js/masonry.js';
import stickyNav from './js/stickyNav.js';
import linkScroll from './js/linkScroll.js';
import modal from './js/modal.js';
import form from './js/form.js';
import galleryModal from './js/galleryModal.js';

stickyNav();
linkScroll();
loadImages();
modal();
form();
masonry();
galleryModal();
